NUMPY

Numpy is a fundemental library for scintifi computing in python it provide support for arrays and matrices,along with a collection of mathematical functions to operate on these data structure.

In [3]:
import numpy as np

## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [2]:
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## attributes of numpy
arr = np.array([[1,2,3,], [4,5,6]])

print("Array:\n", arr)
print("shape:", arr.shape)
print("number of dimensions:", arr.ndim)
print("size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
number of dimensions: 2
size (number of elements): 6
Data type: int64
item size (in bytes): 8


In [9]:
## numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Elements wise addition
print("Addition:", arr1+arr2)

## Element wise substraction
print("subtraction:", arr1-arr2)

Addition: [11 22 33 44 55]
subtraction: [ -9 -18 -27 -36 -45]


In [11]:
## universal function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

##natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [13]:
##array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
arr[0][0]

np.int64(1)

In [19]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [21]:
## modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [22]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [23]:
##statistical concepts--notification
##to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

#calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#normalized_data 
normalized_data= (data - mean) / std_dev
print("normalized_data:", normalized_data)

normalized_data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [3]:
import numpy as np
data = np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean = np.mean(data)
print("mean:", mean)

#median
median = np.median(data)
print("median", median)

#standard deviation
std_dev = np.std(data)
print("standard deviation:", std_dev)

#variance
variance = np.var(data)
print("variance:", variance)

mean: 5.5
median 5.5
standard deviation: 2.8722813232690143
variance: 8.25
